// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUT0/cPhD9Ktb8flIvEVlaetlbKyHUU1FLTwitjD27MU1sdzxZWK3y3atxshA24YCE",
	"UG+OM3/evPfGezChicGj5wTLPSRTYaPz8ZwokBwihYjEDvO1xWTIRXbByyfvIsISEpPzG+gKQElbmWBx",
	"9Nt5xg0SdF0BhH9aR2hheT0OvikOweH2Dg1LrSudfk8R3Aa7m21dobZIOUZb6wSiri+f5U5yJj0b5CpY",
	"iUXfNgLy4vwKCrj8/vNqBPKpQkv1TOWjQSXosfZLo/7A1Nb8ioFN8IyeVzX6DVdzfL8RKRVzXCXW3KYX",
	"pS3A2dlqfd6YURs8QgHOryIFgynB4BsowOP9DM1HdDoLj3WnbEq08+swsWueQ0UKDzuVkLbOCAx2XEv6",
	"8f0WKfVppyeLk4WMEiJ6HR0s4VO+KiBqrvJs5fa05INfQ8oyCslaWn+zsIQv1mZD96Ng4q+DroOMWaIY",
	"a2dyTnmX+hXrd1JO/xOuYQn/lU9LWw4bW+bSXdczlWLwqRf34+L0VT2eW29W0m6W8edMCxylrUWrUmtE",
	"43Vb1zsh8WyxeLOp+0dqrn+FSuRQ9zopH1gZQs1oC8UVqmw25ZIKPn+3CelDUslZFISf3wPhL48PEQ2j",
	"HeAMWMSASAMWWZ+2aTTtegMprQbz5OlywMF55d7ZTuBscMZ9F8ijN0aMS7pBzk/D9R6cQBIzywrqJm+2",
	"hfHWMbVYjIY+NsXNxHiLNzX3gPwFrSn/VWGdOXxUfuw9RWjQbdH2Jjx7BxMKDDHfOrTe/sPOukDOEU8s",
	"Sr8a2fmN0gerdd3fAAAA//+ZzN20LwgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
