// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUTU/cMBD9K9a0Ui8Ru7T0klsrIdRTUUtPCK2MPbsxTWx3PAFWq/z3apwAYZM9IFHU",
	"m+PMx5v33ngHJjQxePScoNxBMhU2Oh9PiQLJIVKISOwwX1tMhlxkF7x88jYilJCYnN9AVwBK2soEi6Pf",
	"zjNukKDrCiD80zpCC+XlOPiqeAgO1zdoWGpd6PR7iuA62O1s6wq1RcoxjrHJB22tE6y6Pn9WZJI8aT5c",
	"aCK9le8GuQpWctG3jaA/O72AAs6//7wYoX+q2FI902mPAQl6rH2Igx+Y2ppfwIQJntHzqka/4WpOiH/N",
	"VsUcV4k1t+mgGQpwdrZ6nzem2gaPUIDzq0jBYEowOA0K8Hg3w/8ez87CY90pzRLt/DpMDJ7nUJHC/VYl",
	"pFtnBAY7riV9//4WKfVpx0fLo6WMEiJ6HR2U8ClfFRA1V3m2BT/YO6QsrjCupe83CyV8sTb7v58DE38d",
	"1B7EzXrFWDuTcxY3qd/IfoXl9J5wDSW8Wzzt+GJY8EUu3XU9TSkGn3qlPy6PX9TjuSFn9exm6X5Os8BR",
	"2lq0KrVGBF63dZ2ddLJcvtrU/Zs2179CJXKoO52UD6wMoWa0heIKVXaackkFn7/bhPQhqeQsCsLPb4Hw",
	"l8f7iIbRDnAGLOI+pAGL7E7bNJq2vYGUVoN58nQ5INtusXO2EywbnLHeGfLo2RHLkm6Q82txuQMneMTG",
	"sny6yTttYbxvTC0Wo4n3HXE1cd3yVZ09ID8gNOW/KqwzgY+yj42nCA26W7S9A0/ewIECQ5y3Dq23/7Gt",
	"zpBzxBOL0q9Gdn6j9IPPuu5vAAAA//+rv303WwgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
