global:
  scrape_interval: 15s
scrape_configs:
  - job_name: proxy
    static_configs:
      - targets: ["proxy:8080"]
  - job_name: nats
    static_configs:
      - targets: ["nats_exporter:7777"]
# TODO: динамическре конфигурирование 
