FROM prom/prometheus:latest

COPY prometheus.yaml /etc/prometheus

ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yaml", \
             "--storage.tsdb.path=/prometheus" ]
